### ISSUE TITLE
Create user_id and user_type

### ISSUE THREAD

**Issue by PlugIN73** [harley/auditable#11]
Hello, how can i insert user_id and user_tyoe into audit table? In my case it's null.

**Comment by harley** [comment]
Hey when you save an "auditable" record, just save the user object under `changed_by` key

For example, this is a line from the Demo section in the [README](https://github.com/harleyttd/auditable/blob/master/README.md) page

```
>> s.update_attributes(:current_page => 3, :action => "modified", :changed_by => User.create(:name => "someone"))
```

**Comment by PlugIN73** [comment]
Yes, but i forgot attr_accessible. Sorry.

**Comment by harley** [comment]
Ah great. i didn't add `attr_accessible` builtin because it may mess up people's `attr_accessible` or `attr_protected` settings so it's a mild convenience there. thanks!
